name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: npm install for frontend
        working-directory: './puhelinluettelo'
        run: npm install
      - name: lint frontend
        working-directory: './puhelinluettelo'
        run: npm run eslint
      - name: run build
        run: npm run build:ui
      #e2e maybe here
      - name: e2e
        uses: cypress-io/github-action@v2
        with:
          command: npm --prefix ./puhelinluettelo run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
      #deploy
      - name: Bump version and push tag
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '#skip') == false
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
      #slack message  