name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: npm install for frontend
        working-directory: './puhelinluettelo'
        run: npm install
      - name: lint frontend
        working-directory: './puhelinluettelo'
        run: npm run eslint
      - name: run build
        run: npm run build:ui
      #e2e maybe here
      - name: e2e
        uses: cypress-io/github-action@v2
        with:
          command: npm --prefix ./puhelinluettelo run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
      #deploy
      - name: deploy
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '#skip') == false
        uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "thawing-dawn-25992" #Must be unique in Heroku
          heroku_email: "j-p.parkkari@iki.fi"
          healthcheck: "https://thawing-dawn-25992.herokuapp.com/health"
          #checkstring: "ok"
          delay: 2
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '#skip') == false
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "main" #this seemed to fix the beta tag problem
      #slack message for failure
      #slack message for success