name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: npm install for frontend
        working-directory: './puhelinluettelo'
        run: npm install
      - name: lint frontend
        working-directory: './puhelinluettelo'
        run: npm run eslint
      - name: run build
        run: npm run build:ui
      #e2e maybe here
      - name: e2e
        uses: cypress-io/github-action@v2
        with:
          command: npm --prefix ./puhelinluettelo run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
      #deploy
      - name: deploy
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '#skip') == false
        uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "thawing-dawn-25992" #Must be unique in Heroku
          heroku_email: "j-p.parkkari@iki.fi"
          healthcheck: "https://thawing-dawn-25992.herokuapp.com/health"
          #checkstring: "ok"
          delay: 2
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '#skip') == false
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "main" #this seemed to fix the beta tag problem
      #slack message for failure
      - name: slack message for failure
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: ${{ failure() }} 
      #slack message for success
      - name: slack message for success
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `a new version deployed to https://fullstack2020-pokedex-jp.herokuapp.com (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: ${{ success() }} 